### ISSUE TITLE
NoSuchNodeError: group ``/`` does not have a child named ``/0/META/COL/id``

### ISSUE THREAD

**Issue by karoraw1** [cmap/l1ktools#13] opened 2016-04-20 19:34 UTC
This is my code:

```
import cmap.io.gct as gct
import cmap.io.plategrp as grp

path_to_gctx_file = "CCLE_expression_CN_muts_GENEE_2010-04-16.gctx"

GCTObject = gct.GCT(path_to_gctx_file)
GCTObject.read()
print(GCTObject.matrix)
```

```
runfile('/home/login/GDrive/Documents/CompGenomicsDataAnalysis/FinalProject/ImportData.py', wdir='/home/login/GDrive/Documents/CompGenomicsDataAnalysis/FinalProject')
Traceback (most recent call last):

  File "<ipython-input-1-e412714c22f4>", line 1, in <module>
    runfile('/home/login/GDrive/Documents/CompGenomicsDataAnalysis/FinalProject/ImportData.py', wdir='/home/login/GDrive/Documents/CompGenomicsDataAnalysis/FinalProject')

  File "/home/login/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/login/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/login/GDrive/Documents/CompGenomicsDataAnalysis/FinalProject/ImportData.py", line 15, in <module>
    GCTObject.read()

  File "cmap/io/gct.py", line 545, in read
    row_inds=row_inds, frame=frame)

  File "cmap/io/gct.py", line 206, in _read_gctx
    col_inds = self.get_gctx_cid_inds(src, match_list=cid)

  File "cmap/io/gct.py", line 249, in get_gctx_cid_inds
    self._open_gctx(src)

  File "cmap/io/gct.py", line 185, in _open_gctx
    self.column_id_node = self._gctx_file.getNode("/0/META/COL", "id")

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/_past.py", line 35, in oldfunc
    return obj(*args, **kwargs)

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/file.py", line 1616, in get_node
    node = self._get_node(nodepath)

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/file.py", line 1555, in _get_node
    node = self._node_manager.get_node(nodepath)

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/file.py", line 436, in get_node
    node = self.node_factory(key)

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/group.py", line 1186, in _g_load_child
    node_type = self._g_check_has_child(childname)

  File "/home/login/anaconda2/lib/python2.7/site-packages/tables/group.py", line 402, in _g_check_has_child
    % (self._v_pathname, name))

NoSuchNodeError: group ``/`` does not have a child named ``/0/META/COL/id``

```

**Comment by tnat1031** [comment] 2016-04-21 16:42
Hi @karoraw1, we are working on a revised version of the python code for parsing GCTX files and will be pushing updates soon, which will include a fix for this problem. Please be on the lookout.

**Comment by tnat1031** [comment] 2016-04-22 12:48
Hi @karoraw1, upon a second look it seems that there may be an issue with the file you are trying to parse. Are you able to parse the example file included in this repo?

`data/modzs_n272x978.gctx`

**Comment by karoraw1** [comment] 2016-04-22 13:32
i didn't try that but you are right, there are issues with my data file relating to sporadic usage of quotation marks.

i did implement all the fixes @rghammonds listed here: 
https://github.com/cmap/l1ktools/issues/1

(aside: the line numbers of the fixes in that issue are slightly lower than what I needed)

and now it works.... sometimes. every other time I read the file, progress halts at around ~3 or 6% when reading in the row information, but if I kill the process and re-run it, it is fine. 

thanks for your quick response.

**Comment by tnat1031** [comment] 2016-04-22 13:39
Ok, thanks for the update. The improvements to the GCTX parser will likely mitigate the other issues you are seeing as well.

**Comment by rghammonds** [comment] 2016-04-28 16:47
The changes I provided 12/2013 no longer seem to be present in master.
I'm not sure why.

As outlined in my original report, the gctx file causing problems is from the CCLE repository maintained at Broad. Either this package should be able to read it, or it should be modified to be readable.  That's the issue.  Broad maintained software has to be able to read Broad produced data sets, right?

original thread
  https://github.com/cmap/l1ktools/issues/1#issuecomment-30558624

current state vs my changes

line 77 of gct.py is 
            command_string += '%s text'
but should be
            command_string += '"%s" text'
lines 185-186 of gct.py are
        self.column_id_node = self._gctx_file.getNode("/0/META/COL", "id")
        self.row_id_node = self._gctx_file.getNode("/0/META/ROW", "id")
but should be
        self.column_id_node = self._gctx_file.getNode("/0/META/COL", "Id")
        self.row_id_node = self._gctx_file.getNode("/0/META/ROW", "Id")
lines 102-104 of gct.py are
        for i,item in enumerate(data_array):
            if isinstance(item,str):
                data_array[i] = '"' + str(item) + '"'
but should be 
        # deal with possible superfluous enclosing quotes in data
        for i,item in enumerate(data_array):
            if isinstance(item,str):
                if len(item) == 0:
                    data_array[i] = '""'
                elif len(item) == 1:
                    data_array[i] = '"%s"' % item
                else:
                    if item[0] == '"' and item[-1] == '"':
                        data_array[i] = str(item)
                    else:
                        data_array[i] = '"%s"' % item

**Comment by rghammonds** [comment] 2016-04-28 16:57
Gah!  have to markdown.  Sorry

line 77 of gct.py
```python
            command_string += '%s text'
```

should be

```python
            command_string += '"%s" text'
```

lines 185-186
```python
        self.column_id_node = self._gctx_file.getNode("/0/META/COL", "id")
        self.row_id_node = self._gctx_file.getNode("/0/META/ROW", "id")
```

but should be

```python
        self.column_id_node = self._gctx_file.getNode("/0/META/COL", "Id")
        self.row_id_node = self._gctx_file.getNode("/0/META/ROW", "Id")
````

lines 102-104 of gct.py 
```python
        for i,item in enumerate(data_array):
            if isinstance(item,str):
                data_array[i] = '"' + str(item) + '"'
```

should be replaced by

```python
        # deal with possible superfluous enclosing quotes in data
        for i,item in enumerate(data_array):
            if isinstance(item,str):
                if len(item) == 0:
                    data_array[i] = '""'
                elif len(item) == 1:
                    data_array[i] = '"%s"' % item
                else:
                    if item[0] == '"' and item[-1] == '"':
                        data_array[i] = str(item)
                    else:
                        data_array[i] = '"%s"' % item
```

**Comment by oena** [comment] 2017-02-08 22:54
Hi @karoraw1 and @rghammonds, not sure how relevant this still is but just wanted to give you an update. We've re-done our Python library pretty much entirely and plan on publishing it as a package shortly; I'm happy to send you the relevant links once we do. Until then, relevant code/documentation can be found at l1ktools/python/broadinstitute_cmap/io/pandasGEXpress; [here's](https://github.com/cmap/l1ktools/blob/master/python/broadinstitute_cmap/io/pandasGEXpress/README.md) a link to the (still in progress) README. 

Also, I'm not as familiar with this problem as the two of you, but from a preliminary read it seems to me that at least part of the problem is a lack of clarity about defining the GCTX file format; for instance, part of the format is that rids and cids must always be located at the datasets pointed to by the (case sensitive) node paths "/0/META/ROW/id" and "/0/META/COL/id" respectively. We're hoping this upcoming publication will eliminate ambiguity on this note, and will also communicate with groups that use the format (like CCLE) on actually following the specifications. Regardless, we appreciate your feedback and PRs, and please continue to let us know about any issues/feature requests/bugs you think of or encounter in the future.

**Closed by oena** 2017-02-08 22:54 UTC
